In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy

In [5]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
we can write numpy as np in short 

In [ ]:
# Advanced Python
# Numpy is a general purpose array-processing package.
# It stands for numerical python, is a fundamental library for numerical and scientific computing in python.
# It provides support for large, multi dimentional arrays and matrices, along with a collection of mathematical functions to operate 
# on these arrays efficiently

In [ ]:
# Numpy is usually imported under the np alias.
# * Alias: In python alias are an alternate name for referring to the same thing.

In [7]:
# import numpy as alias np
import numpy as np

In [ ]:
# Create an array using numpy
# Numpy is used to work with arrays. The array object in Numpy is called ndarray.
# we can create a Numpy ndarray object by using the array() function.

# Array is a linear data structure where all elements are arranged sequentially. It is a collection of elements of same data type stored at contiguous
# memory location

# to create ndarray, we can pass a list, tuple or any array like object into the array() method, and it will be converted into a ndarray:

# three types in arrays: 1D, 2D, 3D


In [9]:
import numpy as np
l = [1,2,3,4]
arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))
print(type(l))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


In [13]:
# 0D array (scalar)
arr_0d = np.array(42)   # A single number - like a point
print(arr_0d)
type(arr_0d)

42


numpy.ndarray

In [17]:
# 1-D array --- a simple list of numbers - like row.

arr_1d = np.array([1,2,3,4])
print("1D Array:", arr_1d)

1D Array: [1 2 3 4]


In [19]:
# 2-D Array(Matrix) -- A table with rows and columns.
arr_2d = np.array([[1,2], [3,4]])
print("2d array:\n", arr_2d)

2d array:
 [[1 2]
 [3 4]]


In [21]:
# 3-D array
arr_3d = np.array([[[1,2,3],[3,4,5],[6,5,3]]])
print("3-D array:\n", arr_3d)

3-D array:
 [[[1 2 3]
  [3 4 5]
  [6 5 3]]]


In [ ]:
# Array inspection -- These functions help you inspect, understand, and convert arrays easily. very useful for
# debugging and data processing in Numpy.

In [25]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

In [27]:
# shape --- tells you the structure

print(arr.shape)  

(2, 3)


In [29]:
# size --- total elements

print(arr.size)

6


In [31]:
# min and max

print(arr.min())
print(arr.max())

1
6


In [35]:
# dtype

print(arr.dtype)

int32


In [37]:
# change data type

arr_float = arr.astype(float)
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]]


In [39]:
# ndim

arr1 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
arr_ndim = arr1.ndim
arr_ndim

3

In [41]:
arr1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [45]:
import numpy as np

arr = np.array([[[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]],

                [[13,14,15,16],
                 [17,18,19,20],
                 [21,22,23,24]]])
print(arr.shape)
arr_ndim

# 1st -- depth (no. of layers), 2nd -- rows per matrix, 3rd -- columns per row

(2, 3, 4)


3

In [1]:
l = [1,2,3,4]
l = l * 4
l

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
# # Why Numpy?
# Memory - Numpy data structures take up less space.
# Performance - They have a need for speed and are faster than list
# Functionallity - Scipy and Numpy have optimized functions such as linear algebra operations built in.

In [5]:
# Different ways of creating an ndarray

# uninitialized
# creating an uninitialized array of a specified shape
import numpy as np
uninitialized_array = np.empty([5,3], dtype = int)
print(uninitialized_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
# Initialized with zeros
# Initializing the arrays with zeros
zeros_array = np.zeros((3,3))
another_zeros_array = np.zeros((4,3), dtype = int)
print(zeros_array)
print(another_zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [1]:
# HW create a 5D array by using all functions ---- identity 2D

import numpy as np

H, W = 100, 100  # dimensions of image
N = 5  # number of other images

# Initialize the mapping array
map_array = np.zeros((H, W, N, 2), dtype=np.int32)

# Example: let's map each pixel to (y+1, x+2) in every nth image
for y in range(H):
    for x in range(W):
        for n in range(N):
            map_array[y, x, n, 0] = y + 1  # y coordinate in nth image
            map_array[y, x, n, 1] = x + 2  # x coordinate in nth image

# Access mapping to the 3rd image (index 2) from pixel at (10, 20)
mapped_y = map_array[10, 20, 2, 0]
mapped_x = map_array[10, 20, 2, 1]

print(f"Pixel (10,20) maps to ({mapped_y}, {mapped_x}) in image 2")


Pixel (10,20) maps to (11, 22) in image 2


In [15]:
import numpy as np   #---- without using identity matrix that is 2D
array_5D = np.zeros((1,2,3,4,5), dtype = int)
print(array_5D)

[[[[[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]]


  [[[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]]]]


In [3]:
import numpy as np

# Step 1: Create a 2D identity matrix
identity_2d = np.identity(3)  # shape: (3, 3)

# Step 2: Expand dimensions to make it 3D
identity_3d = identity_2d[np.newaxis, :, :]  # shape: (1, 3, 3)

# Step 3: Expand to 4D using np.expand_dims
identity_4d = np.expand_dims(identity_3d, axis=0)  # shape: (1, 1, 3, 3)

# Step 4: Use reshape to reshape to (1, 1, 3, 3, 1)
identity_5d = identity_4d.reshape(1, 1, 3, 3, 1)  # shape: (1, 1, 3, 3, 1)

# Optional Step 5: Use tile to repeat and make dimensions larger
identity_5d_tiled = np.tile(identity_5d, (2, 2, 1, 1, 2))  # shape: (2, 2, 3, 3, 2)

print("5D Array Shape:", identity_5d_tiled.shape)
print("5D Array:\n", identity_5d_tiled)


5D Array Shape: (2, 2, 3, 3, 2)
5D Array:
 [[[[[1. 1.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [1. 1.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [1. 1.]]]


  [[[1. 1.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [1. 1.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [1. 1.]]]]



 [[[[1. 1.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [1. 1.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [1. 1.]]]


  [[[1. 1.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [1. 1.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [1. 1.]]]]]


In [5]:
import numpy as np

# Step 1: Create a 2D identity matrix (3x3)
identity_2d = np.identity(3)
print("2D Identity Matrix:\n", identity_2d)

# Step 2: Expand to 3D by stacking
identity_3d = np.stack([identity_2d for _ in range(2)])  # Shape: (2, 3, 3)
print("\n3D Array (2 x 3 x 3):\n", identity_3d)

# Step 3: Expand to 4D by stacking the 3D arrays
identity_4d = np.stack([identity_3d for _ in range(2)])  # Shape: (2, 2, 3, 3)
print("\n4D Array (2 x 2 x 3 x 3):\n", identity_4d)

# Step 4: Expand to 5D by stacking the 4D arrays
identity_5d = np.stack([identity_4d for _ in range(2)])  # Shape: (2, 2, 2, 3, 3)
print("\n5D Array (2 x 2 x 2 x 3 x 3):\n", identity_5d)


2D Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3D Array (2 x 3 x 3):
 [[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]

4D Array (2 x 2 x 3 x 3):
 [[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]]

5D Array (2 x 2 x 2 x 3 x 3):
 [[[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]



 [[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]]


In [13]:
# Initialized with ones
 # Initializing arrays with ones
ones_array = np.ones((3,3))
another_ones_array = np.ones((4,3), dtype = int)
print(ones_array)
print(another_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
# arrays with arange function
# array with values from 0 to N
array_with_range = np.arange(5)
array_with_range

array([0, 1, 2, 3, 4])

In [17]:
array_with_range = np.arange(5,50,3)
array_with_range

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [19]:
# Array with random numbers
# to get an array with random input elements of desired shape
# paramaters for the function - np.full(shape)
random_array = np.random.random((4,3))
print(random_array)

[[0.74953158 0.82873796 0.28744175]
 [0.696871   0.03979547 0.71509839]
 [0.44339906 0.5322705  0.03300599]
 [0.60669058 0.32500056 0.41269046]]


In [27]:
random_integral_array = np.random.randint(0,5, size = (2,3,4))
print(random_integral_array)

[[[4 1 1 1]
  [3 1 2 4]
  [3 3 2 1]]

 [[4 1 2 3]
  [0 4 0 2]
  [4 4 4 0]]]


In [37]:
#np.random.rand(2, 2)
# np.random.randn(2,2)
np.random.randint(1,10,(2,3))

array([[8, 1, 4],
       [4, 5, 1]])

In [39]:
a = np.full((3,3),30)
print(a)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [41]:
# identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
# from existing array
a = np.array([1,2,3,4])
a.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [47]:
# Indexing and slicing of an array
# 1D array
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[2])
print(arr[1:4])

30
[20 30 40]


In [49]:
# 2D array
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2d[1,2])
print(arr2d[0:2,1:])

6
[[2 3]
 [5 6]]


In [51]:
# 3D array
arr3d = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print(arr3d[1,0,1])
print(arr3d[:,1,:])

6
[[3 4]
 [7 8]]


In [9]:
import numpy as np
array_5D = np.zeros((1,2,3,4,5), dtype = int)
print(array_5D)

[[[[[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]]


  [[[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]

   [[0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]
    [0 0 0 0 0]]]]]


In [ ]:
# # Array Manipulation
# array manipulation refers to modifying the structure or elements of an array,such as
# Reshaping - np.reshape(array, shape)
# flattening - np.flatten(array)
# transposing - np.flatten(array)
# Joining or spliting
# Adding or removing elements


Function            Purpose
reshape()           change shape
flatten()           convert to 1d
transpose()         swap axes
concatenate()       join arrays
split()             divide array
stack()             stack arrays along new axis

In [21]:
# reshape() --- changes the shape of the array without changing its data

import numpy as np
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)

c = np.reshape(a,(3,2))
#print(c)


[[1 2 3]
 [4 5 6]]


In [23]:
# flatten() or ravel()--- converts a multi dimentional array into a 1d array.

a = np.array([[1,2], [3,4]])
print(a.flatten())

[1 2 3 4]


In [25]:
# transpose() or T --- swaps rows with columns

a = np.array([[1,2], [3,4]])
print(a.T)

[[1 3]
 [2 4]]


In [31]:
# concatenate() and stack()---used to join arrays

a = np.array([[1,2]])
b = np.array([[3,4]])

print(np.concatenate((a,b), axis = 1))
# print(np.hstack((a,b)))

[[1 2 3 4]]


In [35]:
a = np.array([1,2])
b = np.array([3,4])

np.stack((a,b), axis = 0)

array([[1, 2],
       [3, 4]])

In [ ]:
# add a new 0th axis, turning this into a 2 - row, 2-column array
# Explain

In [37]:
np.stack((a,b),axis = 1)

array([[1, 3],
       [2, 4]])

In [ ]:
# adds a new 1st axis, so each element in a and b becomes a column:
# Explain

In [39]:
import numpy as np
a = np.array([[1,2]])
b = np.array([[3,4]])

print(np.hstack((a,b)))
print("\n", np.vstack((a,b)))

[[1 2 3 4]]

 [[1 2]
 [3 4]]


In [ ]:
# stack, vstack and hstack difference homework

In [41]:
# split() --- used to split arrays into multiple sub-arrays

a = np.array([1,2,3,4,5,6])
print(np.split(a, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]
